.\" Manpage for git-multiclone.
.\" Contact contact@nslab.at.
.TH man 8 "26.02.2018" "1.0.0" "git-multiclone man page"
.SH NAME
git-multiclone \- download multiple repositories at once! This tool provides clone selected or all user/stars repositories from Github (from 'Repositories' and 'Stars' pages).
.SH SYNOPSIS
git-multiclone <option|long-option>
.SH DESCRIPTION
git-multiclone download multiple repositories at once! This tool provides clone selected or all user/stars repositories from Github (from 'Repositories' and 'Stars' pages).
.SH OPTIONS
--help
        show this message

--select-all
        select all available repositories

--tor <port_number>
        set the tor port number
.SH SEE ALSO
https://github.com/trimstray/git-multiclone
.SH BUGS
No known bugs.
.SH AUTHOR
trimstray (contact@nslab.at)
