.\" Manpage for gitpunk.
.\" Contact contact@nslab.at.
.TH man 8 "26.02.2018" "1.0.0" "gitpunk man page"
.SH NAME
gitpunk \- download the repositories that you have marked with an star from github.
.SH SYNOPSIS
gitpunk <option|long-option>
.SH DESCRIPTION
Download the repositories that you have marked with an star from github.
.SH OPTIONS
--help
        show this message

--debug
        displays information on the screen (debug mode)

-c, --check
        check available repositories (report)

-g, --get <all|repo_name>
        get all or specific repositories

-u, --user <username>
        set github username
.SH SEE ALSO
https://github.com/trimstray/gitpunk
.SH BUGS
No known bugs.
.SH AUTHOR
trimstray (contact@nslab.at)
