.\" Manpage for gitpunk.
.\" Contact contact@nslab.at.
.TH man 8 "26.02.2018" "1.0.0" "gitpunk man page"
.SH NAME
gitpunk \- short script description
.SH SYNOPSIS
gitpunk <option|long-option>
.SH DESCRIPTION
gitpunk short long description.
.SH OPTIONS
--help
        show this message

--debug
        displays information on the screen (debug mode)

--verbose
        displays 'info' messages on the screen (verbose mode)

--time
        displays execution time, occurs only with --verbose

-c, --config <file>
        attach an external config file to the script
.SH SEE ALSO
https://github.com/trimstray/gitpunk
.SH BUGS
No known bugs.
.SH AUTHOR
trimstray (contact@nslab.at)
