.\" Manpage for gitpunk.
.\" Contact contact@nslab.at.
.TH man 8 "26.02.2018" "1.0.0" "gitpunk man page"
.SH NAME
gitpunk \- it allows you to clone the repositories (normal repository or marked as a star) of the given user from github.
.SH SYNOPSIS
gitpunk <option|long-option>
.SH DESCRIPTION
It allows you to clone the repositories (normal repository or marked as a star) of the given user from github.
.SH OPTIONS
--help
        show this message

--select-all
        select all available repositories

--tor <port_number>
        set the tor port number
.SH SEE ALSO
https://github.com/trimstray/gitpunk
.SH BUGS
No known bugs.
.SH AUTHOR
trimstray (contact@nslab.at)
